version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Madrid"
    labels:
      - "security"
    assignees:
      - "javierav"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Madrid"
    labels:
      - "security"
    assignees:
      - "javierav"
