require:
  - rubocop-minitest
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude
    - Include
    - Prefixes

AllCops:
  DisplayCopNames: true
  Exclude:
    - "**/bin/**/*"
  NewCops: enable
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
